### ISSUE TITLE
Error on any post request in host app

### ISSUE THREAD

**Issue by francirp** [tatums/telegram#4]
https://www.dropbox.com/s/owfgbns7t92rv35/Screenshot%202015-06-10%2014.20.14.png?dl=0

Is this happening for anyone else?

**Comment by francirp** [comment]
@tatums any idea on this? I'm running a Rails app

**Comment by tatums** [comment]
Hey! It looks like it's trying to acknowledge a message that's no longer there.  

One possibility, You viewed the error page... then somehow the file was removed before you clicked the button.  Keep in mind, you commit a message file with your code (by default in telegram/messages).

Also, there is command to setup necessary config files.  `bundle exec telegram install`

**Comment by tatums** [comment]
I'm also curious to know what the `req.params` are.  If you're still getting the error, paste that in.  It's supposed to contain the file name.  So it can be looked up in the messages directory.  

It should be relatively easy to fix.. via rescue, nil check, or something.

**Comment by francirp** [comment]
Sorry about the delay on this @tatums. Here is the req.params:

{"utf8"=>"✓", "authenticity_token"=>"TBhsS9vY3L2y5g966NmQv6wsuZZ/KpyrxWMG1Z4t/mwlYZOBeID4a2Z0pgFjP26Jhx39zdgGLrOIPrneNdeDTg==", "user"=>{"email"=>"ryan@launchpadlab.com", "password"=>"password"}, "commit"=>"Sign In"}

I basically did the following:

```
# Gemfile
gem 'telegram', :git => "git://github.com/tatums/telegram.git"

# Terminal
bundle
bundle exec telegram install
bundle exec telegram new "My first message"
rails s
# => errors out due to pending message
1 # to dismiss the message
rails s
```

Then whenever I try to submit any post request in the app (in this case, by signing in), it throws that exception. Perhaps a Rails 4 conflict?

**Comment by tatums** [comment]
Check out the most recent from master. Looks like the middleware was accepting **ALL** POST.  whoops!

**Comment by francirp** [comment]
That fixed it. Thanks, @tatums !
